version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: dreamland-mysql
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - dreamland_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uyii2advanced", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  dreamland_mysql:
